<a href="https://colab.research.google.com/github/whythoSanskar/learningml/blob/main/Essential_Mathematics_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Week 1




##Lecture 1



In [ ]:
import numpy as np
a = np.array([1,1,2])
b = np.array([2,3,4])

In [ ]:
print(a+b)

[3 4 6]


In [ ]:
print(a-b)

[-1 -2 -2]


In [ ]:
# Scalar Multiplication
print(3*a)

[3 3 6]


In [ ]:
print(np.linalg.norm(a))

2.449489742783178


In [ ]:
s = np.dot(a,b)
print(s)

13


## Lecture 2

In [1]:
import numpy as np
P = np.array([[1,7], [2,1], [3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [2]:
Q = np.array([[1,0], [3,2], [2,3]])
print(Q)

[[1 0]
 [3 2]
 [2 3]]


In [4]:
C1 = np.add(P,Q)
print(C1)

[[2 7]
 [5 3]
 [5 5]]


In [6]:
C2 = np.subtract(P,Q)
print(C2)

[[ 0  7]
 [-1 -1]
 [ 1 -1]]


In [8]:
R = np.array([[1,7,8], [2,3,4]])
print(R)

[[1 7 8]
 [2 3 4]]


In [9]:
C3 = np.dot(P,R)
print(C3)

[[15 28 36]
 [ 4 17 20]
 [ 7 27 32]]


In [15]:
det = np.linalg.det(C3)
print(det)

0.0


In [17]:
# A singular matrix is one that is not invertible. 
s2= np.linalg.inv(C3)
print(s2)

LinAlgError: ignored

In [18]:
M = np.array([[1,-1], [2,3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
